"""scm.models.network: Network-related models."""
# scm/models/network/__init__.py

from .aggregate_interface import (
    AggregateInterfaceCreateModel,
    AggregateInterfaceResponseModel,
    AggregateInterfaceUpdateModel,
    AggregateLayer2,
    AggregateLayer3,
)
from .ethernet_interface import (
    EthernetInterfaceCreateModel,
    EthernetInterfaceResponseModel,
    EthernetInterfaceUpdateModel,
    EthernetLayer2,
    EthernetLayer3,
    EthernetTap,
)
from .ike_crypto_profile import (
    DHGroup,
    EncryptionAlgorithm,
    HashAlgorithm,
    IKECryptoProfileCreateModel,
    IKECryptoProfileResponseModel,
    IKECryptoProfileUpdateModel,
    LifetimeDays,
    LifetimeHours,
    LifetimeMinutes,
    LifetimeSeconds,
)
from .ike_gateway import (
    Authentication,
    IKEGatewayCreateModel,
    IKEGatewayResponseModel,
    IKEGatewayUpdateModel,
    LocalId,
    LocalIdType,
    PeerAddress,
    PeerId,
    PeerIdType,
    Protocol,
    ProtocolCommon,
    ProtocolVersion,
)
from .ipsec_crypto_profile import (  # These are already imported from ike_crypto_profile; LifetimeSeconds,; LifetimeMinutes,; LifetimeHours,; LifetimeDays,
    AhAuthentication,
    AhConfig,
    DhGroup,
    EspAuthentication,
    EspConfig,
    EspEncryption,
    IPsecCryptoProfileBaseModel,
    IPsecCryptoProfileCreateModel,
    IPsecCryptoProfileResponseModel,
    IPsecCryptoProfileUpdateModel,
    LifesizeGB,
    LifesizeKB,
    LifesizeMB,
    LifesizeTB,
)
from .nat_rules import (
    DestinationTranslation,
    DistributionMethod,
    DnsRewrite,
    DnsRewriteDirection,
    DynamicIp,
    DynamicIpAndPort,
    InterfaceAddress,
    NatRuleCreateModel,
    NatRuleResponseModel,
    NatRuleUpdateModel,
    SourceTranslation,
    StaticIp,
)
from .layer2_subinterface import (
    Layer2SubinterfaceCreateModel,
    Layer2SubinterfaceResponseModel,
    Layer2SubinterfaceUpdateModel,
)
from .layer3_subinterface import (
    Layer3SubinterfaceCreateModel,
    Layer3SubinterfaceResponseModel,
    Layer3SubinterfaceUpdateModel,
)
from .loopback_interface import (
    LoopbackInterfaceCreateModel,
    LoopbackInterfaceResponseModel,
    LoopbackInterfaceUpdateModel,
)
from .security_zone import (
    DeviceAcl,
    NetworkConfig,
    NetworkInterfaceType,
    SecurityZoneCreateModel,
    SecurityZoneResponseModel,
    SecurityZoneUpdateModel,
    UserAcl,
)
from .tunnel_interface import (
    TunnelInterfaceCreateModel,
    TunnelInterfaceResponseModel,
    TunnelInterfaceUpdateModel,
)
from .vlan_interface import (
    VlanInterfaceCreateModel,
    VlanInterfaceResponseModel,
    VlanInterfaceUpdateModel,
)
from ._interface_common import (
    AdjustTcpMss,
    ArpEntry,
    ArpEntryWithInterface,
    BonjourConfig,
    DdnsConfig,
    DhcpClient,
    Ipv6Address,
    Ipv6Config,
    Ipv6ConfigExtended,
    Ipv6NeighborDiscovery,
    LacpConfig,
    LinkDuplex,
    LinkSpeed,
    LinkState,
    LldpConfig,
    NdpProxyConfig,
    PoeConfig,
    PppoeConfig,
    SendHostname,
    StaticIpEntry,
)

__all__ = [
    # Shared Interface Common Models
    "AdjustTcpMss",
    "ArpEntry",
    "ArpEntryWithInterface",
    "BonjourConfig",
    "DdnsConfig",
    "DhcpClient",
    "Ipv6Address",
    "Ipv6Config",
    "Ipv6ConfigExtended",
    "Ipv6NeighborDiscovery",
    "LacpConfig",
    "LinkDuplex",
    "LinkSpeed",
    "LinkState",
    "LldpConfig",
    "NdpProxyConfig",
    "PoeConfig",
    "PppoeConfig",
    "SendHostname",
    "StaticIpEntry",
    # Aggregate Interface
    "AggregateInterfaceCreateModel",
    "AggregateInterfaceUpdateModel",
    "AggregateInterfaceResponseModel",
    "AggregateLayer2",
    "AggregateLayer3",
    # Ethernet Interface
    "EthernetInterfaceCreateModel",
    "EthernetInterfaceUpdateModel",
    "EthernetInterfaceResponseModel",
    "EthernetLayer2",
    "EthernetLayer3",
    "EthernetTap",
    # Layer2 Subinterface
    "Layer2SubinterfaceCreateModel",
    "Layer2SubinterfaceUpdateModel",
    "Layer2SubinterfaceResponseModel",
    # Layer3 Subinterface
    "Layer3SubinterfaceCreateModel",
    "Layer3SubinterfaceUpdateModel",
    "Layer3SubinterfaceResponseModel",
    # Loopback Interface
    "LoopbackInterfaceCreateModel",
    "LoopbackInterfaceUpdateModel",
    "LoopbackInterfaceResponseModel",
    # Tunnel Interface
    "TunnelInterfaceCreateModel",
    "TunnelInterfaceUpdateModel",
    "TunnelInterfaceResponseModel",
    # VLAN Interface
    "VlanInterfaceCreateModel",
    "VlanInterfaceUpdateModel",
    "VlanInterfaceResponseModel",
    # IKE Crypto Profile
    "IKECryptoProfileCreateModel",
    "IKECryptoProfileUpdateModel",
    "IKECryptoProfileResponseModel",
    "HashAlgorithm",
    "EncryptionAlgorithm",
    "DHGroup",
    "LifetimeSeconds",
    "LifetimeMinutes",
    "LifetimeHours",
    "LifetimeDays",
    # IKE Gateway
    "IKEGatewayCreateModel",
    "IKEGatewayUpdateModel",
    "IKEGatewayResponseModel",
    "PeerIdType",
    "LocalIdType",
    "ProtocolVersion",
    "Authentication",
    "PeerId",
    "LocalId",
    "Protocol",
    "ProtocolCommon",
    "PeerAddress",
    # IPsec Crypto Profile
    "IPsecCryptoProfileBaseModel",
    "IPsecCryptoProfileCreateModel",
    "IPsecCryptoProfileUpdateModel",
    "IPsecCryptoProfileResponseModel",
    "DhGroup",
    "EspEncryption",
    "EspAuthentication",
    "AhAuthentication",
    "LifesizeKB",
    "LifesizeMB",
    "LifesizeGB",
    "LifesizeTB",
    "EspConfig",
    "AhConfig",
    # NAT Rules
    "NatRuleCreateModel",
    "NatRuleUpdateModel",
    "NatRuleResponseModel",
    "DynamicIpAndPort",
    "StaticIp",
    "InterfaceAddress",
    "DestinationTranslation",
    "DistributionMethod",
    "SourceTranslation",
    "DynamicIp",
    "DnsRewrite",
    "DnsRewriteDirection",
    # Security Zone
    "SecurityZoneCreateModel",
    "SecurityZoneUpdateModel",
    "SecurityZoneResponseModel",
    "NetworkInterfaceType",
    "NetworkConfig",
    "UserAcl",
    "DeviceAcl",
]
