repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10  # Match the version in pyproject.toml
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=600']
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key
