services:
  sdk:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - POETRY_VIRTUALENVS_CREATE=false
    tty: true
    command: sleep infinity

  docs:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - POETRY_VIRTUALENVS_CREATE=false
    command: poetry run mkdocs serve -a 0.0.0.0:8000
