services:
  sdk:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - POETRY_VIRTUALENVS_CREATE=false
    tty: true
    command: sleep infinity
