import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar mirrors the former MkDocs `nav:` tree (see git history of mkdocs.yml).
const sidebars: SidebarsConfig = {
  docs: [
    {type: 'doc', id: 'index', label: "Home"},
    {
      type: 'category',
      label: "About",
      items: [
        {type: 'doc', id: 'about/introduction', label: "Introduction"},
        {type: 'doc', id: 'about/architecture', label: "Architecture"},
        {type: 'doc', id: 'about/installation', label: "Installation"},
        {type: 'doc', id: 'about/getting-started', label: "Getting Started"},
        {type: 'doc', id: 'about/troubleshooting', label: "Troubleshooting"},
        {type: 'doc', id: 'about/contributing', label: "Contributing"},
        {type: 'doc', id: 'about/release-notes', label: "Release Notes"},
        {type: 'doc', id: 'about/license', label: "License"},
      ],
    },
    {
      type: 'category',
      label: "Services",
      items: [
        {type: 'doc', id: 'sdk/index', label: "Overview"},
        {type: 'doc', id: 'sdk/auth', label: "Auth"},
        {type: 'doc', id: 'sdk/client', label: "Client"},
        {type: 'doc', id: 'sdk/config/base_object', label: "BaseObject"},
        {
          type: 'category',
          label: "Deployment",
          items: [
            {type: 'doc', id: 'sdk/config/deployment/index', label: "Overview"},
            {type: 'doc', id: 'sdk/config/deployment/bandwidth_allocations', label: "Bandwidth Allocations"},
            {type: 'doc', id: 'sdk/config/deployment/bgp_routing', label: "BGP Routing"},
            {type: 'doc', id: 'sdk/config/deployment/internal_dns_servers', label: "Internal DNS Servers"},
            {type: 'doc', id: 'sdk/config/deployment/network_locations', label: "Network Locations"},
            {type: 'doc', id: 'sdk/config/deployment/remote_networks', label: "Remote Networks"},
            {type: 'doc', id: 'sdk/config/deployment/service_connections', label: "Service Connections"},
          ],
        },
        {
          type: 'category',
          label: "Mobile Agent",
          items: [
            {type: 'doc', id: 'sdk/config/mobile_agent/index', label: "Overview"},
            {type: 'doc', id: 'sdk/config/mobile_agent/auth_settings', label: "Authentication Settings"},
            {type: 'doc', id: 'sdk/config/mobile_agent/agent_versions', label: "Agent Versions"},
            {type: 'doc', id: 'sdk/config/mobile_agent/agent_profiles', label: "Application Settings (Agent Profiles)"},
            {type: 'doc', id: 'sdk/config/mobile_agent/forwarding_profiles', label: "Forwarding Profiles"},
            {type: 'doc', id: 'sdk/config/mobile_agent/forwarding_profile_destinations', label: "Forwarding Profile Destinations"},
            {type: 'doc', id: 'sdk/config/mobile_agent/forwarding_profile_source_applications', label: "Forwarding Profile Source Applications"},
            {type: 'doc', id: 'sdk/config/mobile_agent/forwarding_profile_user_locations', label: "Forwarding Profile User Locations"},
            {type: 'doc', id: 'sdk/config/mobile_agent/forwarding_profile_regional_and_custom_proxies', label: "Forwarding Profile Regional and Custom Proxies"},
            {type: 'doc', id: 'sdk/config/mobile_agent/global_settings', label: "Global Settings"},
            {type: 'doc', id: 'sdk/config/mobile_agent/infrastructure_settings', label: "Infrastructure Settings"},
            {type: 'doc', id: 'sdk/config/mobile_agent/tunnel_profiles', label: "Tunnel Profiles"},
          ],
        },
        {
          type: 'category',
          label: "Network",
          items: [
            {type: 'doc', id: 'sdk/config/network/index', label: "Overview"},
            {type: 'doc', id: 'sdk/config/network/aggregate_interface', label: "Aggregate Interfaces"},
            {type: 'doc', id: 'sdk/config/network/dhcp_interface', label: "DHCP Interface"},
            {type: 'doc', id: 'sdk/config/network/ethernet_interface', label: "Ethernet Interfaces"},
            {type: 'doc', id: 'sdk/config/network/ike_crypto_profile', label: "IKE Crypto Profiles"},
            {type: 'doc', id: 'sdk/config/network/ike_gateway', label: "IKE Gateways"},
            {type: 'doc', id: 'sdk/config/network/interface_management_profile', label: "Interface Management Profiles"},
            {type: 'doc', id: 'sdk/config/network/ipsec_crypto_profile', label: "IPsec Crypto Profiles"},
            {type: 'doc', id: 'sdk/config/network/ipsec_tunnel', label: "IPsec Tunnels"},
            {type: 'doc', id: 'sdk/config/network/layer2_subinterface', label: "Layer2 Subinterfaces"},
            {type: 'doc', id: 'sdk/config/network/layer3_subinterface', label: "Layer3 Subinterfaces"},
            {type: 'doc', id: 'sdk/config/network/logical_router', label: "Logical Routers"},
            {type: 'doc', id: 'sdk/config/network/loopback_interface', label: "Loopback Interfaces"},
            {type: 'doc', id: 'sdk/config/network/dns_proxy', label: "DNS Proxies"},
            {type: 'doc', id: 'sdk/config/network/nat_rules', label: "NAT Rules"},
            {type: 'doc', id: 'sdk/config/network/pbf_rule', label: "PBF Rules"},
            {type: 'doc', id: 'sdk/config/network/qos_profile', label: "QoS Profiles"},
            {type: 'doc', id: 'sdk/config/network/qos_rule', label: "QoS Rules"},
            {type: 'doc', id: 'sdk/config/network/security_zone', label: "Security Zones"},
            {type: 'doc', id: 'sdk/config/network/tunnel_interface', label: "Tunnel Interfaces"},
            {type: 'doc', id: 'sdk/config/network/vlan_interface', label: "VLAN Interfaces"},
            {type: 'doc', id: 'sdk/config/network/zone_protection_profile', label: "Zone Protection Profiles"},
            {type: 'doc', id: 'sdk/config/network/bgp_address_family_profile', label: "BGP Address Family Profiles"},
            {type: 'doc', id: 'sdk/config/network/bgp_auth_profile', label: "BGP Auth Profiles"},
            {type: 'doc', id: 'sdk/config/network/bgp_filtering_profile', label: "BGP Filtering Profiles"},
            {type: 'doc', id: 'sdk/config/network/bgp_redistribution_profile', label: "BGP Redistribution Profiles"},
            {type: 'doc', id: 'sdk/config/network/bgp_route_map', label: "BGP Route Maps"},
            {type: 'doc', id: 'sdk/config/network/bgp_route_map_redistribution', label: "BGP Route Map Redistribution"},
            {type: 'doc', id: 'sdk/config/network/ospf_auth_profile', label: "OSPF Auth Profiles"},
            {type: 'doc', id: 'sdk/config/network/route_access_list', label: "Route Access Lists"},
            {type: 'doc', id: 'sdk/config/network/route_prefix_list', label: "Route Prefix Lists"},
          ],
        },
        {
          type: 'category',
          label: "Objects",
          items: [
            {type: 'doc', id: 'sdk/config/objects/index', label: "Overview"},
            {type: 'doc', id: 'sdk/config/objects/address', label: "Addresses"},
            {type: 'doc', id: 'sdk/config/objects/address_group', label: "Address Groups"},
            {type: 'doc', id: 'sdk/config/objects/application', label: "Applications"},
            {type: 'doc', id: 'sdk/config/objects/application_filters', label: "Application Filters"},
            {type: 'doc', id: 'sdk/config/objects/application_group', label: "Application Groups"},
            {type: 'doc', id: 'sdk/config/objects/auto_tag_actions', label: "Auto Tag Actions"},
            {type: 'doc', id: 'sdk/config/objects/dynamic_user_group', label: "Dynamic User Groups"},
            {type: 'doc', id: 'sdk/config/objects/external_dynamic_lists', label: "External Dynamic Lists"},
            {type: 'doc', id: 'sdk/config/objects/hip_object', label: "HIP Objects"},
            {type: 'doc', id: 'sdk/config/objects/hip_profile', label: "HIP Profiles"},
            {type: 'doc', id: 'sdk/config/objects/http_server_profiles', label: "HTTP Server Profiles"},
            {type: 'doc', id: 'sdk/config/objects/log_forwarding_profile', label: "Log Forwarding Profiles"},
            {type: 'doc', id: 'sdk/config/objects/quarantined_devices', label: "Quarantined Devices"},
            {type: 'doc', id: 'sdk/config/objects/region', label: "Regions"},
            {type: 'doc', id: 'sdk/config/objects/schedules', label: "Schedules"},
            {type: 'doc', id: 'sdk/config/objects/service', label: "Services"},
            {type: 'doc', id: 'sdk/config/objects/service_group', label: "Service Groups"},
            {type: 'doc', id: 'sdk/config/objects/syslog_server_profiles', label: "Syslog Server Profiles"},
            {type: 'doc', id: 'sdk/config/objects/tag', label: "Tags"},
          ],
        },
        {
          type: 'category',
          label: "Security Services",
          items: [
            {type: 'doc', id: 'sdk/config/security_services/index', label: "Overview"},
            {type: 'doc', id: 'sdk/config/security_services/anti_spyware_profile', label: "Anti-Spyware Profiles"},
            {type: 'doc', id: 'sdk/config/security_services/authentication_rule', label: "Authentication Rules"},
            {type: 'doc', id: 'sdk/config/security_services/decryption_profile', label: "Decryption Profiles"},
            {type: 'doc', id: 'sdk/config/security_services/decryption_rule', label: "Decryption Rules"},
            {type: 'doc', id: 'sdk/config/security_services/dns_security_profile', label: "DNS Security Profiles"},
            {type: 'doc', id: 'sdk/config/security_services/security_rule', label: "Security Rules"},
            {type: 'doc', id: 'sdk/config/security_services/url_categories', label: "URL Categories"},
            {type: 'doc', id: 'sdk/config/security_services/wildfire_antivirus', label: "WildFire Antivirus Profiles"},
            {type: 'doc', id: 'sdk/config/security_services/vulnerability_protection_profile', label: "Vulnerability Protection Profiles"},
            {type: 'doc', id: 'sdk/config/security_services/app_override_rule', label: "App Override Rules"},
            {type: 'doc', id: 'sdk/config/security_services/file_blocking_profile', label: "File Blocking Profiles"},
            {type: 'doc', id: 'sdk/config/security_services/url_access_profile', label: "URL Access Profiles"},
          ],
        },
        {
          type: 'category',
          label: "Identity",
          items: [
            {type: 'doc', id: 'sdk/config/identity/index', label: "Overview"},
            {type: 'doc', id: 'sdk/config/identity/authentication_profile', label: "Authentication Profiles"},
            {type: 'doc', id: 'sdk/config/identity/kerberos_server_profile', label: "Kerberos Server Profiles"},
            {type: 'doc', id: 'sdk/config/identity/ldap_server_profile', label: "LDAP Server Profiles"},
            {type: 'doc', id: 'sdk/config/identity/radius_server_profile', label: "RADIUS Server Profiles"},
            {type: 'doc', id: 'sdk/config/identity/saml_server_profile', label: "SAML Server Profiles"},
            {type: 'doc', id: 'sdk/config/identity/tacacs_server_profile', label: "TACACS+ Server Profiles"},
          ],
        },
        {
          type: 'category',
          label: "Setup",
          items: [
            {type: 'doc', id: 'sdk/config/setup/index', label: "Overview"},
            {type: 'doc', id: 'sdk/config/setup/folder', label: "Folders"},
            {type: 'doc', id: 'sdk/config/setup/label', label: "Labels"},
            {type: 'doc', id: 'sdk/config/setup/snippet', label: "Snippets"},
            {type: 'doc', id: 'sdk/config/setup/device', label: "Devices"},
            {type: 'doc', id: 'sdk/config/setup/variable', label: "Variables"},
          ],
        },
        {
          type: 'category',
          label: "Insights",
          items: [
            {type: 'doc', id: 'sdk/insights/index', label: "Overview"},
            {type: 'doc', id: 'sdk/insights/alerts', label: "Alerts"},
          ],
        },
        {
          type: 'category',
          label: "Operations",
          items: [
            {type: 'doc', id: 'sdk/operations/index', label: "Overview"},
            {type: 'doc', id: 'sdk/operations/local_config', label: "Local Config"},
            {type: 'doc', id: 'sdk/operations/device_operations', label: "Device Operations"},
          ],
        },
        {
          type: 'category',
          label: "Incidents",
          items: [
            {type: 'doc', id: 'sdk/incidents/index', label: "Overview"},
            {type: 'doc', id: 'sdk/incidents/incidents', label: "Incidents"},
          ],
        },
        {type: 'doc', id: 'sdk/exceptions', label: "Exceptions"},
      ],
    },
    {
      type: 'category',
      label: "Data Models",
      items: [
        {type: 'doc', id: 'sdk/models/index', label: "Overview"},
        {
          type: 'category',
          label: "Deployment",
          items: [
            {type: 'doc', id: 'sdk/models/deployment/index', label: "Overview"},
            {type: 'doc', id: 'sdk/models/deployment/bandwidth_allocation_models', label: "Bandwidth Allocations"},
            {type: 'doc', id: 'sdk/models/deployment/bgp_routing_models', label: "BGP Routing"},
            {type: 'doc', id: 'sdk/models/deployment/internal_dns_servers_models', label: "Internal DNS Servers"},
            {type: 'doc', id: 'sdk/models/deployment/network_locations', label: "Network Locations"},
            {type: 'doc', id: 'sdk/models/deployment/remote_networks_models', label: "Remote Networks"},
            {type: 'doc', id: 'sdk/models/deployment/service_connections_models', label: "Service Connections"},
          ],
        },
        {
          type: 'category',
          label: "Mobile Agent",
          items: [
            {type: 'doc', id: 'sdk/models/mobile_agent/index', label: "Overview"},
            {type: 'doc', id: 'sdk/models/mobile_agent/auth_settings_models', label: "Authentication Settings"},
            {type: 'doc', id: 'sdk/models/mobile_agent/agent_versions_models', label: "Agent Versions"},
            {type: 'doc', id: 'sdk/models/mobile_agent/agent_profiles_models', label: "Application Settings (Agent Profiles)"},
            {type: 'doc', id: 'sdk/models/mobile_agent/forwarding_profiles_models', label: "Forwarding Profiles"},
            {type: 'doc', id: 'sdk/models/mobile_agent/forwarding_profile_destinations_models', label: "Forwarding Profile Destinations"},
            {type: 'doc', id: 'sdk/models/mobile_agent/forwarding_profile_source_applications_models', label: "Forwarding Profile Source Applications"},
            {type: 'doc', id: 'sdk/models/mobile_agent/forwarding_profile_user_locations_models', label: "Forwarding Profile User Locations"},
            {type: 'doc', id: 'sdk/models/mobile_agent/forwarding_profile_regional_and_custom_proxies_models', label: "Forwarding Profile Regional and Custom Proxies"},
            {type: 'doc', id: 'sdk/models/mobile_agent/global_settings_models', label: "Global Settings"},
            {type: 'doc', id: 'sdk/models/mobile_agent/infrastructure_settings_models', label: "Infrastructure Settings"},
            {type: 'doc', id: 'sdk/models/mobile_agent/tunnel_profiles_models', label: "Tunnel Profiles"},
          ],
        },
        {
          type: 'category',
          label: "Network",
          items: [
            {type: 'doc', id: 'sdk/models/network/index', label: "Overview"},
            {type: 'doc', id: 'sdk/models/network/aggregate_interface_models', label: "Aggregate Interfaces"},
            {type: 'doc', id: 'sdk/models/network/dhcp_interface_models', label: "DHCP Interface"},
            {type: 'doc', id: 'sdk/models/network/ethernet_interface_models', label: "Ethernet Interfaces"},
            {type: 'doc', id: 'sdk/models/network/ike_crypto_profile_models', label: "IKE Crypto Profiles"},
            {type: 'doc', id: 'sdk/models/network/ike_gateway_models', label: "IKE Gateways"},
            {type: 'doc', id: 'sdk/models/network/interface_management_profile_models', label: "Interface Management Profiles"},
            {type: 'doc', id: 'sdk/models/network/ipsec_crypto_profile_models', label: "IPsec Crypto Profiles"},
            {type: 'doc', id: 'sdk/models/network/ipsec_tunnel_models', label: "IPsec Tunnels"},
            {type: 'doc', id: 'sdk/models/network/layer2_subinterface_models', label: "Layer2 Subinterfaces"},
            {type: 'doc', id: 'sdk/models/network/layer3_subinterface_models', label: "Layer3 Subinterfaces"},
            {type: 'doc', id: 'sdk/models/network/logical_router_models', label: "Logical Routers"},
            {type: 'doc', id: 'sdk/models/network/loopback_interface_models', label: "Loopback Interfaces"},
            {type: 'doc', id: 'sdk/models/network/dns_proxy_models', label: "DNS Proxy Models"},
            {type: 'doc', id: 'sdk/models/network/nat_rule_models', label: "NAT Rules"},
            {type: 'doc', id: 'sdk/models/network/pbf_rule_models', label: "PBF Rule Models"},
            {type: 'doc', id: 'sdk/models/network/qos_profile_models', label: "QoS Profile Models"},
            {type: 'doc', id: 'sdk/models/network/qos_rule_models', label: "QoS Rule Models"},
            {type: 'doc', id: 'sdk/models/network/security_zone_models', label: "Security Zones"},
            {type: 'doc', id: 'sdk/models/network/tunnel_interface_models', label: "Tunnel Interfaces"},
            {type: 'doc', id: 'sdk/models/network/vlan_interface_models', label: "VLAN Interfaces"},
            {type: 'doc', id: 'sdk/models/network/zone_protection_profile_models', label: "Zone Protection Profiles"},
            {type: 'doc', id: 'sdk/models/network/bgp_address_family_profile_models', label: "BGP Address Family Profiles"},
            {type: 'doc', id: 'sdk/models/network/bgp_auth_profile_models', label: "BGP Auth Profiles"},
            {type: 'doc', id: 'sdk/models/network/bgp_filtering_profile_models', label: "BGP Filtering Profiles"},
            {type: 'doc', id: 'sdk/models/network/bgp_redistribution_profile_models', label: "BGP Redistribution Profiles"},
            {type: 'doc', id: 'sdk/models/network/bgp_route_map_models', label: "BGP Route Maps"},
            {type: 'doc', id: 'sdk/models/network/bgp_route_map_redistribution_models', label: "BGP Route Map Redistribution"},
            {type: 'doc', id: 'sdk/models/network/ospf_auth_profile_models', label: "OSPF Auth Profiles"},
            {type: 'doc', id: 'sdk/models/network/route_access_list_models', label: "Route Access Lists"},
            {type: 'doc', id: 'sdk/models/network/route_prefix_list_models', label: "Route Prefix Lists"},
            {type: 'doc', id: 'sdk/models/network/nat_rules_models', label: "NAT Rules (Legacy)"},
          ],
        },
        {
          type: 'category',
          label: "Objects",
          items: [
            {type: 'doc', id: 'sdk/models/objects/index', label: "Overview"},
            {type: 'doc', id: 'sdk/models/objects/address_models', label: "Addresses"},
            {type: 'doc', id: 'sdk/models/objects/address_group_models', label: "Address Groups"},
            {type: 'doc', id: 'sdk/models/objects/application_models', label: "Applications"},
            {type: 'doc', id: 'sdk/models/objects/application_filters_models', label: "Application Filters"},
            {type: 'doc', id: 'sdk/models/objects/application_group_models', label: "Application Groups"},
            {type: 'doc', id: 'sdk/models/objects/auto_tag_actions_models', label: "Auto Tag Actions"},
            {type: 'doc', id: 'sdk/models/objects/dynamic_user_group_models', label: "Dynamic User Groups"},
            {type: 'doc', id: 'sdk/models/objects/external_dynamic_lists_models', label: "External Dynamic Lists"},
            {type: 'doc', id: 'sdk/models/objects/hip_object_models', label: "HIP Objects"},
            {type: 'doc', id: 'sdk/models/objects/hip_profile_models', label: "HIP Profiles"},
            {type: 'doc', id: 'sdk/models/objects/http_server_profiles_models', label: "HTTP Server Profiles"},
            {type: 'doc', id: 'sdk/models/objects/log_forwarding_profile_models', label: "Log Forwarding Profiles"},
            {type: 'doc', id: 'sdk/models/objects/quarantined_devices_models', label: "Quarantined Devices"},
            {type: 'doc', id: 'sdk/models/objects/region_models', label: "Regions"},
            {type: 'doc', id: 'sdk/models/objects/schedules_models', label: "Schedules"},
            {type: 'doc', id: 'sdk/models/objects/service_models', label: "Services"},
            {type: 'doc', id: 'sdk/models/objects/service_group_models', label: "Service Groups"},
            {type: 'doc', id: 'sdk/models/objects/syslog_server_profiles_models', label: "Syslog Server Profiles"},
            {type: 'doc', id: 'sdk/models/objects/tag_models', label: "Tags"},
          ],
        },
        {
          type: 'category',
          label: "Operations",
          items: [
            {type: 'doc', id: 'sdk/models/operations/index', label: "Overview"},
            {type: 'doc', id: 'sdk/models/operations/candidate_push', label: "Candidate Push"},
            {type: 'doc', id: 'sdk/models/operations/jobs', label: "Jobs"},
            {type: 'doc', id: 'sdk/models/operations/local_config_models', label: "Local Config"},
            {type: 'doc', id: 'sdk/models/operations/device_operations_models', label: "Device Operations"},
          ],
        },
        {
          type: 'category',
          label: "Incidents",
          items: [
            {type: 'doc', id: 'sdk/models/incidents/index', label: "Overview"},
            {type: 'doc', id: 'sdk/models/incidents/incidents_models', label: "Incidents"},
          ],
        },
        {
          type: 'category',
          label: "Security Services",
          items: [
            {type: 'doc', id: 'sdk/models/security_services/index', label: "Overview"},
            {type: 'doc', id: 'sdk/models/security_services/anti_spyware_profile_models', label: "Anti-Spyware Profiles"},
            {type: 'doc', id: 'sdk/models/security_services/authentication_rule_models', label: "Authentication Rules"},
            {type: 'doc', id: 'sdk/models/security_services/decryption_profile_models', label: "Decryption Profiles"},
            {type: 'doc', id: 'sdk/models/security_services/decryption_rule_models', label: "Decryption Rules"},
            {type: 'doc', id: 'sdk/models/security_services/dns_security_profile_models', label: "DNS Security Profiles"},
            {type: 'doc', id: 'sdk/models/security_services/security_rule_models', label: "Security Rules"},
            {type: 'doc', id: 'sdk/models/security_services/url_categories_models', label: "URL Categories"},
            {type: 'doc', id: 'sdk/models/security_services/wildfire_antivirus_profile_models', label: "WildFire Antivirus Profiles"},
            {type: 'doc', id: 'sdk/models/security_services/vulnerability_protection_profile_models', label: "Vulnerability Protection Profiles"},
            {type: 'doc', id: 'sdk/models/security_services/app_override_rule_models', label: "App Override Rules"},
            {type: 'doc', id: 'sdk/models/security_services/file_blocking_profile_models', label: "File Blocking Profiles"},
            {type: 'doc', id: 'sdk/models/security_services/url_access_profile_models', label: "URL Access Profiles"},
          ],
        },
        {
          type: 'category',
          label: "Identity",
          items: [
            {type: 'doc', id: 'sdk/models/identity/index', label: "Overview"},
            {type: 'doc', id: 'sdk/models/identity/authentication_profile_models', label: "Authentication Profiles"},
            {type: 'doc', id: 'sdk/models/identity/kerberos_server_profile_models', label: "Kerberos Server Profiles"},
            {type: 'doc', id: 'sdk/models/identity/ldap_server_profile_models', label: "LDAP Server Profiles"},
            {type: 'doc', id: 'sdk/models/identity/radius_server_profile_models', label: "RADIUS Server Profiles"},
            {type: 'doc', id: 'sdk/models/identity/saml_server_profile_models', label: "SAML Server Profiles"},
            {type: 'doc', id: 'sdk/models/identity/tacacs_server_profile_models', label: "TACACS+ Server Profiles"},
          ],
        },
        {
          type: 'category',
          label: "Setup",
          items: [
            {type: 'doc', id: 'sdk/models/setup/index', label: "Overview"},
            {type: 'doc', id: 'sdk/models/setup/folder_models', label: "Folders"},
            {type: 'doc', id: 'sdk/models/setup/label_models', label: "Labels"},
            {type: 'doc', id: 'sdk/models/setup/snippet_models', label: "Snippets"},
            {type: 'doc', id: 'sdk/models/setup/device_models', label: "Devices"},
            {type: 'doc', id: 'sdk/models/setup/variable_models', label: "Variables"},
          ],
        },
        {
          type: 'category',
          label: "Insights",
          items: [
            {type: 'doc', id: 'sdk/models/insights/index', label: "Overview"},
            {type: 'doc', id: 'sdk/models/insights/alerts_models', label: "Alerts"},
          ],
        },
      ],
    },
  ],
};

export default sidebars;
